FROM golang:alpine3.23 

WORKDIR /home/src/app/

RUN mkdir controller indexer

COPY governance-indexer/go.mod governance-indexer/go.sum ./indexer/
COPY controller/ ./controller/

WORKDIR /home/src/app/indexer

RUN go mod download

COPY governance-indexer/ .

CMD [ "go", "run", "cmd/main.go" ]