FROM golang:alpine3.23 

WORKDIR /home/src/app/

RUN mkdir controller telegramBot

COPY telegramBot/go.mod telegramBot/go.sum ./telegramBot/
COPY controller/ ./controller/

WORKDIR /home/src/app/telegramBot

RUN go mod download

COPY telegramBot/ .

CMD [ "go", "run", "cmd/main.go" ]